// <auto-generated />
namespace WebBanHang.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class oo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(oo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201811080118132_oo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
